export { getUserName } from './getUserName.js';
export { getEvenGameAnswer } from './getEvenGameAnswer.js';
export { generator } from './generator.js';
export { isEven } from './isEven.js';
export { evenGame } from './evenGame.js';
export { getOperation } from './getOperation.js';
export { calcGameRightAnswer } from './calcGameRightAnswer.js';
export { getCalcGameAnswer } from './getCalcGameAnswer.js';
export { calcGame } from './calcGame.js';